### ISSUE TITLE
Change the venue's `website` text into a hyperlink

### ISSUE THREAD

**Issue by storrer** [Jonathanlouiskirk/reVENUE#75]
## Overview
This venue `website` field is displayed through the `individual_venue.html` template. Right now the URL is displayed as text. Change it into a hyperlink.
![image](https://user-images.githubusercontent.com/13088830/172275471-e9a6b0e9-b34b-4e05-9a49-6b33a76a2119.png)

## Technical Notes
Place the `website` variable inside an anchor element's `href` field and again in the text content of that element.

**Comment by jonfaustothen** [comment]
resolved on different issue
