### ISSUE TITLE
Change venue address in `individual_venue.html` to conventional address format

### ISSUE THREAD

**Issue by storrer** [Jonathanlouiskirk/reVENUE#76]
## Overview
In the `individual_venue.html` template the venue data is displayed one field per line. Change the structure of the template to display the address in conventional format. Here is an example of that format:
![image](https://user-images.githubusercontent.com/13088830/172276619-4d17fa8f-29a9-43c3-9edd-46a2085b5e8f.png)

**Comment by jonfaustothen** [comment]
updated.
